version: "3.12-slim"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"

  google_search:
    image: google_search:latest
    build:
      context: .
      dockerfile: Dockerfile.microservice
    ports:
      - "8001:8001"
    depends_on:
      - backend
